### PR TITLE
removed mock for tests and use config template instead

### PR DESCRIPTION
**Pull request by ellesmith88**

### CODE REVIEW

**Comment by cehbrecht** [comment]
@ellesmith88 I had an issue yesterday with another PR to rook that the `ROOCS_CONFIG` environment variable had no effect. It worked when I was moving the setting of the environment variable to `tests/__init__.py`:
https://github.com/roocs/rook/blob/ca4549060b75552442322cd277ff1504e8402a44/tests/__init__.py#L11

**Comment by ellesmith88** [comment]
@cehbrecht That's interesting, I didn't have that problem but I've called `write_roocs_cfg()` in `conftest.py`. I hadn't thought about putting it in `tests/__init__.py`. Should I move it to there do you think?

**Comment by cehbrecht** [comment]
> @cehbrecht That's interesting, I didn't have that problem but I've called `write_roocs_cfg()` in `conftest.py`. I hadn't thought about putting it in `tests/__init__.py`. Should I move it to there do you think?

The environment needs to be set before the configs are loaded ... I guess. I have removed `conftest.py` in rook because I had no fixtures. But I could re-add it for the env setting ... might be the better place. I will try in rook.

**Comment by cehbrecht** [comment]
@ellesmith88 done with https://github.com/roocs/rook/pull/42

**Pull request merged**
